In [1]:
#Programa: numpy_2.ipynb
#@autor: @programacionUdec - logprog1
#Propósito: aprender a usar los nparray
#fecha: miercoles 10 de Nov

In [2]:
import numpy as np

lista=list(range(0,20,1))
array=np.arange(0,20,2)


print(lista,type(lista))
print(array,array.shape,type(array))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19] <class 'list'>
[ 0  2  4  6  8 10 12 14 16 18] (10,) <class 'numpy.ndarray'>


In [3]:
print(array[3:5])
print(array[7])

[6 8]
14


In [4]:
#puedo redimensionar el array. es decir pasar de array 1D a uno ND. 
#ejemplo 1D a una matriz 4X5

array2=np.arange(0,20).reshape(4,5)#reshape(rows,cols)

print(array2,array2.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)


In [5]:
print(array2[1][4])#acceder a un elemento particula de la matrix 

9


In [6]:
y=np.array([ [1,2],[3,4] ]) #matriz 2X2
print(y,y.shape)

[[1 2]
 [3 4]] (2, 2)


In [7]:
y2=np.matrix('1 2; 3 4')

print(y2,y2.shape)

[[1 2]
 [3 4]] (2, 2)


In [8]:
y3=np.matrix([ [1,2],[3,4] ])

print(y3,y3.shape)

[[1 2]
 [3 4]] (2, 2)


In [9]:
b=np.array([ [1,2,3,6],[4,5,6,4] ])
print(b,b.shape)

[[1 2 3 6]
 [4 5 6 4]] (2, 4)


In [10]:
z=np.matrix([ [1,2,3],[4,5,6] ])
print(z,z.shape)


[[1 2 3]
 [4 5 6]] (2, 3)


In [11]:
print(b[0][0],b[0][1],b[1][2])

1 2 6


In [12]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 20]])
print(a,a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 20]] (4, 3)


In [14]:
Vivian= a > 2

print(Vivian)

[[False False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [16]:
print(a[Vivian])

[ 3  4  5  6  7  8  9 10 11 20]


In [18]:

test = np.array([0, 1, 2, 5, 0])
states =np.array([0, 2])

mask=np.in1d(test,states)

print(mask)
print(test[mask])

[ True False  True False  True]
[0 2 0]


In [20]:
mask2=np.in1d(states,test)

print(mask2)
print(states[mask2])

[ True  True]
[0 2]


In [23]:
mask3=np.in1d(test,test)

mask3

array([ True,  True,  True,  True,  True])

In [24]:
#operaciones básicas 

x = np.array([[1,2],[3,4]], dtype=np.float64)  #los enteros los convierte en tipo flotante
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [26]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [28]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [30]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [31]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [32]:
print(x.T)

[[1. 3.]
 [2. 4.]]


In [34]:
print(array2.T)
#https://numpy.org/doc/stable/reference/routines.linalg.html

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
