In [1]:
#Programa: numpy_2.ipynb
#@autor: @programacionUdec - logprog1
#Propósito: aprender a usar los nparray
#fecha: miercoles 10 de Nov

In [13]:
import numpy as np

lista=list(range(0,20,2))
array=np.arange(0,20,2)

print(lista,type(lista))
print(array,type(array),array.shape)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18] <class 'list'>
[ 0  2  4  6  8 10 12 14 16 18] <class 'numpy.ndarray'> (10,)


In [14]:
print(array[3:5])

[6 8]


In [17]:
#puedo redimensionar el array. es decir pasar de array 1D a uno ND. 
#ejemplo 1D a una matriz 4X5
array2=np.arange(0,20).reshape(4,5)#reshape(rows,cols)

print(array2,array2.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)


In [21]:
print(array2[1][4])#acceder a un elemento particula de la matrix creada: nombre_array[row,col]

9


In [29]:
y=np.array( [ [1,2],[3,2]  ] ) #matriz 2X2
print(y,y.shape,type(y))

[[1 2]
 [3 2]] (2, 2) <class 'numpy.ndarray'>


In [31]:
complejo=np.array([1,2,3], dtype=complex) #array de numeros complejos

print(complejo,complejo.shape)

[1.+0.j 2.+0.j 3.+0.j] (3,)


In [32]:
b=np.array([  [1,2,3],[4,5,6]   ])

print(b,b.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [36]:
z=np.matrix([  [1,2,3],[4,5,6]   ])

print(z,z.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [40]:
print(b[0][0],b[0][1],b[1][2])

1 2 6


In [42]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 20]])

print(a,a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 20]] (4, 3)


In [43]:
TF= a > 2
print(TF)


[[False False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [44]:
print( a[TF] )

[ 3  4  5  6  7  8  9 10 11 20]


In [46]:
# in1d Test whether each element of a 1-D array is also present in a second array.

test = np.array([0, 1, 2, 5, 0])
states =np.array([0, 2])

mask=np.in1d(test,states)#Buscar si los elementos de states se encuentran en el array test

print(mask)
print(test[mask])

[ True False  True False  True]
[0 2 0]


In [48]:
mask2=np.in1d(states,test)

print(mask2)
print(states[mask2])

[ True  True]
[0 2]


In [50]:
#operaciones básicas 


x = np.array([[1,2],[3,4]], dtype=np.float64)  #los enteros los convierte en tipo flotante
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [52]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [53]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [55]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [56]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [57]:
print(x.T)  #transpuesta

#https://numpy.org/doc/stable/reference/routines.linalg.html

[[1. 3.]
 [2. 4.]]
